stages:
  - deploy

default:
  image: node:20

pages:
  stage: deploy
  script:
    - cd app
    - npm ci || npm install
    - npm run build
    - cd ..
    - ls server/public
    - rm -rf public
    - mkdir -p public
    - cp -r server/public/. public/
  artifacts:
    paths:
      - public
    expire_in: 1 year
  only:
    - main