stages:
  - build

default:
  image: node:20

build:
  stage: build
  script:
    - cd app
    - npm ci || npm install
    - npm run build
  artifacts:
    paths:
      - app/dist
    expire_in: 1 week
  only:
    - main
